// AUTO-GENERATED by scripts/generate-audio.mjs — do not edit by hand.
// Metro needs static require() calls to bundle local assets, so this map
// bridges the content model's audio.src paths to bundled modules. Re-run the
// generator after changing VOCAB to refresh it.

export const AUDIO_ASSETS: Record<string, number> = {
  "audio/bg/banan__baba.wav": require("../assets/audio/bg/banan__baba.wav"),
  "audio/bg/grozde__baba.wav": require("../assets/audio/bg/grozde__baba.wav"),
  "audio/bg/kotka__default.mp3": require("../assets/audio/bg/kotka__default.mp3"),
  "audio/bg/krusha__baba.wav": require("../assets/audio/bg/krusha__baba.wav"),
  "audio/bg/kuche__default.mp3": require("../assets/audio/bg/kuche__default.mp3"),
  "audio/bg/ptitsa__default.mp3": require("../assets/audio/bg/ptitsa__default.mp3"),
  "audio/bg/riba__default.mp3": require("../assets/audio/bg/riba__default.mp3"),
  "audio/bg/yabalka__baba.wav": require("../assets/audio/bg/yabalka__baba.wav"),
  "audio/en/apple__default.wav": require("../assets/audio/en/apple__default.wav"),
  "audio/en/banana__default.wav": require("../assets/audio/en/banana__default.wav"),
  "audio/en/bird__default.mp3": require("../assets/audio/en/bird__default.mp3"),
  "audio/en/cat__default.mp3": require("../assets/audio/en/cat__default.mp3"),
  "audio/en/dog__default.mp3": require("../assets/audio/en/dog__default.mp3"),
  "audio/en/fish__default.mp3": require("../assets/audio/en/fish__default.mp3"),
  "audio/en/grapes__default.wav": require("../assets/audio/en/grapes__default.wav"),
  "audio/en/pear__default.wav": require("../assets/audio/en/pear__default.wav"),
};
