// generate-audio.mjs — dev-time placeholder audio generator.
//
// WHY THIS EXISTS: every VocabItem needs a recording in each language, but we
// don't have family voices recorded yet. This script fills any MISSING clip
// with neutral text-to-speech so the app has real, working audio out of the
// box. Real recordings (баба's voice, etc.) can be dropped in later via the
// parent setup screen and this script will leave them untouched.
//
// IMPORTANT — this runs at BUILD/DEV time only. It writes .mp3 files into
// assets/audio/ which are then BUNDLED into the app. The app itself makes no
// network calls at runtime; that hard rule (no network in the MVP, content is
// bundled) is preserved. Think of this as a stand-in for a voice actor, run by
// a developer, not something the shipped app ever touches.
//
// SINGLE SOURCE OF TRUTH: it reads VOCAB straight from content-model.ts (via
// Node type-stripping) so the word list never drifts. It also rewrites
// lib/audioAssets.ts, the static require() map Metro needs, so that file never
// has to be hand-edited when vocab is added.
//
// Usage:
//   node --experimental-strip-types scripts/generate-audio.mjs         # fill gaps
//   node --experimental-strip-types scripts/generate-audio.mjs --force # regenerate all TTS clips
//
// Note: TTS has one voice per language, so every generated clip for a language
// sounds the same regardless of the voiceId in its filename. The voiceId is
// just a stable slot a real recording can replace later.

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { VOCAB } from "../content/content-model.ts";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ASSETS = join(ROOT, "assets");
const force = process.argv.includes("--force");

// Collect every (src, lang, text) the content model expects.
const clips = [];
for (const item of Object.values(VOCAB)) {
  for (const lang of Object.keys(item.audio)) {
    clips.push({ src: item.audio[lang].src, lang, text: item.labels[lang] });
  }
}

function fetchTts(text, lang, outPath) {
  const url =
    "https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob" +
    `&tl=${encodeURIComponent(lang)}&q=${encodeURIComponent(text)}`;
  // curl honours the environment's HTTPS proxy; Node's fetch would need extra
  // wiring. -f fails on HTTP errors so we don't write an error page as "audio".
  execFileSync("curl", ["-fsS", "-A", "Mozilla/5.0", "-o", outPath, url], {
    stdio: ["ignore", "ignore", "inherit"],
  });
  const size = statSync(outPath).size;
  if (size < 512) throw new Error(`suspiciously small clip (${size} bytes) for "${text}"`);
}

let generated = 0;
let skipped = 0;
for (const clip of clips) {
  const outPath = join(ASSETS, clip.src);
  const isMp3 = clip.src.endsWith(".mp3");

  if (existsSync(outPath) && !force) {
    skipped++;
    continue;
  }
  if (!isMp3) {
    // The TTS endpoint returns MP3. A missing non-.mp3 clip (e.g. a legacy
    // .wav) can't be produced here — new vocab should use .mp3 paths.
    if (!existsSync(outPath)) {
      console.warn(`SKIP ${clip.src}: only .mp3 can be generated (missing non-mp3 clip)`);
    } else {
      skipped++;
    }
    continue;
  }

  mkdirSync(dirname(outPath), { recursive: true });
  console.log(`TTS  ${clip.lang}  "${clip.text}"  ->  ${clip.src}`);
  fetchTts(clip.text, clip.lang, outPath);
  generated++;
}

// Rewrite the static require() map from the full vocab set (deduped, sorted).
const uniqueSrcs = [...new Set(clips.map((c) => c.src))].sort();
const entries = uniqueSrcs
  .map((src) => `  ${JSON.stringify(src)}: require(${JSON.stringify("../assets/" + src)}),`)
  .join("\n");
const banner =
  "// AUTO-GENERATED by scripts/generate-audio.mjs — do not edit by hand.\n" +
  "// Metro needs static require() calls to bundle local assets, so this map\n" +
  "// bridges the content model's audio.src paths to bundled modules. Re-run the\n" +
  "// generator after changing VOCAB to refresh it.\n\n";
writeFileSync(
  join(ROOT, "lib", "audioAssets.ts"),
  `${banner}export const AUDIO_ASSETS: Record<string, number> = {\n${entries}\n};\n`,
);

console.log(`\nDone. Generated ${generated}, skipped ${skipped} existing. Wrote lib/audioAssets.ts (${uniqueSrcs.length} clips).`);
